CREATE TABLE public.my_categoria
(
    categoria_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    categoria_descricao character varying(16) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_categoria PRIMARY KEY (categoria_id)
);

CREATE TABLE public.my_desenvolvedor
(
    desenvolvedor_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    desenvolvedor_nome character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT pk_desenvolvedor PRIMARY KEY (desenvolvedor_id)
);

CREATE TABLE public.my_editora
(
    editora_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    editora_nome character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT pk_editora PRIMARY KEY (editora_id)
);

CREATE TABLE public.my_engine
(
    engine_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    engine_nome character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT pk_engine PRIMARY KEY (engine_id)
);

CREATE TABLE public.my_funcao
(
    funcao_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    funcao_descricao character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_funcao PRIMARY KEY (funcao_id)
);

CREATE TABLE public.my_pessoa
(
    pessoa_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    pessoa_nome character varying(32) COLLATE pg_catalog."default" NOT NULL,
    pessoa_foto bytea,
    pessoa_data_nascimento date DEFAULT '2000-01-01'::date,
    pessoa_biografia text COLLATE pg_catalog."default",
    CONSTRAINT pk_pessoa PRIMARY KEY (pessoa_id)
);

CREATE TABLE public.my_pessoa_galeria
(
    pessoa_galeria_foto_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    pessoa_id integer NOT NULL,
    pessoa_galeria_foto bytea,
    CONSTRAINT pk_pessoa_galeria_foto PRIMARY KEY (pessoa_galeria_foto_id),
    CONSTRAINT my_pessoa_galeria_pessoa_id_fkey FOREIGN KEY (pessoa_id)
        REFERENCES public.my_pessoa (pessoa_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_publicador
(
    publicador_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    publicador_nome character varying(64) COLLATE pg_catalog."default",
    CONSTRAINT pk_publicador PRIMARY KEY (publicador_id)
);

CREATE TABLE public.my_saga
(
    saga_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    saga_nome character varying(64) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_saga PRIMARY KEY (saga_id)
);

CREATE TABLE public.my_slfj
(
    slfj_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    slfj_titulo character varying(64) COLLATE pg_catalog."default" NOT NULL,
    slfj_foto bytea,
    slfj_sinopse text COLLATE pg_catalog."default",
    categoria_id integer,
    saga_id integer,
    CONSTRAINT pk_slfj PRIMARY KEY (slfj_id),
    CONSTRAINT my_slfj_categoria_id_fkey FOREIGN KEY (categoria_id)
        REFERENCES public.my_categoria (categoria_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT my_slfj_saga_id_fkey FOREIGN KEY (saga_id)
        REFERENCES public.my_saga (saga_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_slfj_galeria
(
    slfj_galeria_foto_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    slfj_id integer NOT NULL,
    slfj_galeria_foto bytea,
    CONSTRAINT pk_slfj_galeria_foto PRIMARY KEY (slfj_galeria_foto_id),
    CONSTRAINT my_slfj_galeria_slfj_id_fkey FOREIGN KEY (slfj_id)
        REFERENCES public.my_slfj (slfj_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_filme_pg
(
    filme_pg_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    filme_pg_rate character varying(8) COLLATE pg_catalog."default" NOT NULL,
    filme_pg_descricao character varying(256) COLLATE pg_catalog."default",
    CONSTRAINT pk_filme_pg PRIMARY KEY (filme_pg_id)
);

CREATE TABLE public.my_filme
(
    filme_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    slfj_id integer NOT NULL,
    filme_pg_id integer,
    filme_duracao integer,
    filme_data_lancamento date DEFAULT '2000-01-01'::date,
    CONSTRAINT pk_filme PRIMARY KEY (filme_id),
    CONSTRAINT my_filme_filme_pg_id_fkey FOREIGN KEY (filme_pg_id)
        REFERENCES public.my_filme_pg (filme_pg_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT,
    CONSTRAINT my_filme_slfj_id_fkey FOREIGN KEY (slfj_id)
        REFERENCES public.my_slfj (slfj_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_livro
(
    livro_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    slfj_id integer NOT NULL,
    livro_isbn integer NOT NULL,
    livro_numero_paginas integer,
    livro_data_lancamento date DEFAULT '2000-01-01'::date,
    editora_id integer NOT NULL,
    CONSTRAINT pk_livro PRIMARY KEY (livro_id),
    CONSTRAINT my_livro_editora_id_fkey FOREIGN KEY (editora_id)
        REFERENCES public.my_editora (editora_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_livro_slfj_id_fkey FOREIGN KEY (slfj_id)
        REFERENCES public.my_slfj (slfj_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public.my_tv_pg
(
    tv_pg_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    tv_pg_descricao character varying(256) COLLATE pg_catalog."default",
    tv_pg_rate character varying(8) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_tv_pg PRIMARY KEY (tv_pg_id)
);

CREATE TABLE public.my_serie
(
    serie_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    slfj_id integer NOT NULL,
    tv_pg_id integer,
    serie_data_lancamento date DEFAULT '2000-01-01'::date,
    CONSTRAINT pk_serie PRIMARY KEY (serie_id),
    CONSTRAINT my_serie_slfj_id_fkey FOREIGN KEY (slfj_id)
        REFERENCES public.my_slfj (slfj_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_serie_tv_pg_id_fkey FOREIGN KEY (tv_pg_id)
        REFERENCES public.my_tv_pg (tv_pg_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE RESTRICT
);

CREATE TABLE public.my_temporada
(
    temporada_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    serie_id integer NOT NULL,
    temporada_nome character varying(64) COLLATE pg_catalog."default",
    temporada_foto bytea,
    temporada_sinopse text COLLATE pg_catalog."default",
    CONSTRAINT pk_temporada PRIMARY KEY (temporada_id),
    CONSTRAINT my_temporada_serie_id_fkey FOREIGN KEY (serie_id)
        REFERENCES public.my_serie (serie_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_temporada_galeria
(
    temporada_galeria_foto_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    temporada_id integer NOT NULL,
    temporada_galeria_foto bytea,
    CONSTRAINT pk_temporada_galeria_foto PRIMARY KEY (temporada_galeria_foto_id),
    CONSTRAINT my_temporada_galeria_temporada_id_fkey FOREIGN KEY (temporada_id)
        REFERENCES public.my_temporada (temporada_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public.my_temporada_video
(
    temporada_video_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    temporada_id integer NOT NULL,
    temporada_video_link character varying(256) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_temporada_video PRIMARY KEY (temporada_video_id),
    CONSTRAINT my_temporada_video_temporada_id_fkey FOREIGN KEY (temporada_id)
        REFERENCES public.my_temporada (temporada_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public.my_episodio
(
    episodio_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    temporada_id integer NOT NULL,
    episodio_nome character varying(64) COLLATE pg_catalog."default",
    episodio_foto bytea,
    episodio_sinopse text COLLATE pg_catalog."default",
    CONSTRAINT pk_episodio PRIMARY KEY (episodio_id),
    CONSTRAINT my_episodio_temporada_id_fkey FOREIGN KEY (temporada_id)
        REFERENCES public.my_temporada (temporada_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_episodio_galeria
(
    episodio_galeria_foto_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    episodio_id integer NOT NULL,
    episodio_galeria_foto bytea,
    CONSTRAINT pk_episodio_galeria_foto PRIMARY KEY (episodio_galeria_foto_id),
    CONSTRAINT my_episodio_galeria_episodio_id_fkey FOREIGN KEY (episodio_id)
        REFERENCES public.my_episodio (episodio_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public.my_jogo
(
    jogo_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    slfj_id integer,
    jogo_data_lancamento date DEFAULT '2000-01-01'::date,
    desenvolvedor_id integer,
    publicador_id integer,
    engine_id integer,
    CONSTRAINT pk_jogo PRIMARY KEY (jogo_id),
    CONSTRAINT my_jogo_desenvolvedor_id_fkey FOREIGN KEY (desenvolvedor_id)
        REFERENCES public.my_desenvolvedor (desenvolvedor_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_jogo_engine_id_fkey FOREIGN KEY (engine_id)
        REFERENCES public.my_engine (engine_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_jogo_publicador_id_fkey FOREIGN KEY (publicador_id)
        REFERENCES public.my_publicador (publicador_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_jogo_slfj_id_fkey FOREIGN KEY (slfj_id)
        REFERENCES public.my_slfj (slfj_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_slfj_pessoa_funcao
(
    slfj_id integer NOT NULL,
    funcao_id integer NOT NULL,
    pessoa_id integer NOT NULL,
    CONSTRAINT pk_slfj_pessoa_funcao PRIMARY KEY (slfj_id, funcao_id, pessoa_id),
    CONSTRAINT my_slfj_pessoa_funcao_funcao_id_fkey FOREIGN KEY (funcao_id)
        REFERENCES public.my_funcao (funcao_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_slfj_pessoa_funcao_pessoa_id_fkey FOREIGN KEY (pessoa_id)
        REFERENCES public.my_pessoa (pessoa_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_slfj_pessoa_funcao_slfj_id_fkey FOREIGN KEY (slfj_id)
        REFERENCES public.my_slfj (slfj_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_tipo
(
    tipo_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    tipo_descricao character varying(16) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_tipo PRIMARY KEY (tipo_id)
);

CREATE TABLE public.my_slfj_tipo
(
    slfj_id integer NOT NULL,
    tipo_id integer NOT NULL,
    CONSTRAINT pk_slfj_tipo PRIMARY KEY (slfj_id, tipo_id),
    CONSTRAINT my_slfj_tipo_slfj_id_fkey FOREIGN KEY (slfj_id)
        REFERENCES public.my_slfj (slfj_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_slfj_tipo_tipo_id_fkey FOREIGN KEY (tipo_id)
        REFERENCES public.my_tipo (tipo_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_slfj_video
(
    slfj_video_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    slfj_id integer NOT NULL,
    slfj_video_link character varying(256) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT pk_slfj_video PRIMARY KEY (slfj_video_id),
    CONSTRAINT my_slfj_video_slfj_id_fkey FOREIGN KEY (slfj_id)
        REFERENCES public.my_slfj (slfj_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);

CREATE TABLE public.my_user
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_name character varying(32) COLLATE pg_catalog."default" NOT NULL,
    user_password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    user_email character varying(256) COLLATE pg_catalog."default" NOT NULL,
    user_foto bytea,
    user_aniversario date DEFAULT '2000-01-01'::date,
    user_data_cricao date DEFAULT CURRENT_DATE,
    user_descricao text COLLATE pg_catalog."default",
    CONSTRAINT pk_user PRIMARY KEY (user_id),
    CONSTRAINT my_user_user_email_key UNIQUE (user_email)
,
    CONSTRAINT my_user_user_name_key UNIQUE (user_name)

);

CREATE TABLE public.my_user_episodio_rating
(
    episodio_id integer NOT NULL,
    user_id integer NOT NULL,
    user_episodio_rating double precision,
    CONSTRAINT pk_user_episodio_rating PRIMARY KEY (episodio_id, user_id),
    CONSTRAINT my_user_episodio_rating_episodio_id_fkey FOREIGN KEY (episodio_id)
        REFERENCES public.my_episodio (episodio_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_user_episodio_rating_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.my_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_user_filme_rating
(
    filme_id integer NOT NULL,
    user_id integer NOT NULL,
    user_filme_rating double precision,
    CONSTRAINT pk_user_filme_rating PRIMARY KEY (filme_id, user_id),
    CONSTRAINT my_user_filme_rating_filme_id_fkey FOREIGN KEY (filme_id)
        REFERENCES public.my_filme (filme_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_user_filme_rating_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.my_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_user_jogo_rating
(
    jogo_id integer NOT NULL,
    user_id integer NOT NULL,
    user_jogo_rating double precision,
    CONSTRAINT pk_user_jogo_rating PRIMARY KEY (jogo_id, user_id),
    CONSTRAINT my_user_jogo_rating_jogo_id_fkey FOREIGN KEY (jogo_id)
        REFERENCES public.my_jogo (jogo_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_user_jogo_rating_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.my_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_user_livro_rating
(
    livro_id integer NOT NULL,
    user_id integer NOT NULL,
    user_livro_rating double precision,
    CONSTRAINT pk_user_livro_rating PRIMARY KEY (livro_id, user_id),
    CONSTRAINT my_user_livro_rating_livro_id_fkey FOREIGN KEY (livro_id)
        REFERENCES public.my_livro (livro_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_user_livro_rating_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.my_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_user_pessoa_historico
(
    user_pessoa_historico_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    pessoa_id integer NOT NULL,
    user_historico_pessoa_data_historico timestamp without time zone,
    CONSTRAINT pk_user_pessoa_historico PRIMARY KEY (user_pessoa_historico_id),
    CONSTRAINT my_user_pessoa_historico_pessoa_id_fkey FOREIGN KEY (pessoa_id)
        REFERENCES public.my_pessoa (pessoa_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_user_pessoa_historico_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.my_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_user_slfj_comentario
(
    user_slfj_comentario_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    slfj_id integer NOT NULL,
    user_id integer NOT NULL,
    user_slfj_comentario_data_comentario timestamp without time zone DEFAULT CURRENT_DATE,
    user_slfj_comentario_texto text COLLATE pg_catalog."default",
    CONSTRAINT pk_user_slfj_comentario PRIMARY KEY (user_slfj_comentario_id),
    CONSTRAINT my_user_slfj_comentario_slfj_id_fkey FOREIGN KEY (slfj_id)
        REFERENCES public.my_slfj (slfj_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_user_slfj_comentario_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.my_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_user_slfj_comentario_rating
(
    user_slfj_comentario_id integer NOT NULL,
    user_id integer NOT NULL,
    user_slfj_comentario_rating double precision,
    CONSTRAINT pk_user_slfj_comentario_rating PRIMARY KEY (user_slfj_comentario_id, user_id),
    CONSTRAINT my_user_slfj_comentario_rating_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.my_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_user_slfj_comentario_rating_user_slfj_comentario_id_fkey FOREIGN KEY (user_slfj_comentario_id)
        REFERENCES public.my_user_slfj_comentario (user_slfj_comentario_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);

CREATE TABLE public.my_user_slfj_historico
(
    user_slfj_historico_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    slfj_id integer NOT NULL,
    user_historico_slfj_data_historico timestamp without time zone,
    CONSTRAINT pk_user_slfj_historico PRIMARY KEY (user_slfj_historico_id),
    CONSTRAINT my_user_slfj_historico_slfj_id_fkey FOREIGN KEY (slfj_id)
        REFERENCES public.my_slfj (slfj_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT my_user_slfj_historico_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES public.my_user (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
);
