CREATE TABLE my_Company
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    name character varying(64) NOT NULL,
    CONSTRAINT pkCompany PRIMARY KEY (id)
);

CREATE TABLE my_ParentAdvisory
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    rate character varying(64) NOT NULL,
    description text,
    CONSTRAINT pkParentAdvisory PRIMARY KEY (id)
);

CREATE TABLE my_Engine
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    name character varying(64) NOT NULL,
    CONSTRAINT pkEngine PRIMARY KEY (id)
);

CREATE TABLE my_Saga
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    name character varying(64) NOT NULL,
    description text,
    CONSTRAINT pkSaga PRIMARY KEY (id)
);

CREATE TABLE my_Game
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    title character varying(128) NOT NULL,
    photo bytea,
    releaseDate date,
    synopsis text,
    engineId int REFERENCES my_Engine(id) ON DELETE CASCADE NOT NULL,
    parentAdvisoryId int REFERENCES my_ParentAdvisory(id) ON DELETE CASCADE NOT NULL,
    publicadorId int REFERENCES my_Company(id) ON DELETE CASCADE NOT NULL,
    sagaId int REFERENCES my_Saga(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkGame PRIMARY KEY (id)
);

-- 5

CREATE TABLE my_GameGallery
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    photo bytea NOT NULL,
    gameId int REFERENCES my_Game(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkGameGallery PRIMARY KEY (id)
);

CREATE TABLE my_Developers
(
    gameId int REFERENCES my_Game(id) ON DELETE CASCADE NOT NULL,
    companyId int REFERENCES my_Company(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkDevelopers PRIMARY KEY (gameId, companyId)
);

CREATE TABLE my_Movie
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    title character varying(128) NOT NULL,
    photo bytea,
    releaseDate date,
    synopsis text,
    duration int,
    parentAdvisoryId int REFERENCES my_ParentAdvisory(id) ON DELETE CASCADE NOT NULL,
    sagaId int REFERENCES my_Saga(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkMovie PRIMARY KEY (id)
);

CREATE TABLE my_MovieGallery
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    photo bytea NOT NULL,
    movieId int REFERENCES my_Movie(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkMovieGallery PRIMARY KEY (id)
);

-- 10

CREATE TABLE my_PublishingCompany
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    name character varying(64) NOT NULL,
    CONSTRAINT pkPublishingCompany PRIMARY KEY (id)
);

CREATE TABLE my_Book
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    title character varying(128) NOT NULL,
    photo bytea,
    releaseDate date,
    synopsis text,
    publishingCompanyId int REFERENCES my_PublishingCompany(id) ON DELETE CASCADE  NOT NULL,
    sagaId int REFERENCES my_Saga(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkBook PRIMARY KEY (id)
);

CREATE TABLE my_Series
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    title character varying(128) NOT NULL,
    photo bytea,
    releaseDate date,
    synopsis text,
    parentAdvisoryId int REFERENCES my_ParentAdvisory(id) ON DELETE CASCADE  NOT NULL,
    sagaId int REFERENCES my_Saga(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkSeries PRIMARY KEY (id)
);

CREATE TABLE my_SeriesGallery
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    photo bytea NOT NULL,
    seriesId int REFERENCES my_Series(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkSeriesGallery PRIMARY KEY (id)
);

-- 15

CREATE TABLE my_Season
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    title character varying(128) NOT NULL,
    photo bytea,
    releaseDate date,
    synopsis text,
    seriesId int REFERENCES my_Series(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkSeason PRIMARY KEY (id)
);

CREATE TABLE my_SeasonGallery
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    photo bytea NOT NULL,
    seasonId int REFERENCES my_Season(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkSeasonGallery PRIMARY KEY (id)
);

CREATE TABLE my_Episode
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    title character varying(128) NOT NULL,
    photo bytea,
    releaseDate date,
    synopsis text,
    seasonId int REFERENCES my_Season(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkEpisode PRIMARY KEY (id)
);

CREATE TABLE my_EpisodeGallery
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    photo bytea NOT NULL,
    episodeId int REFERENCES my_Episode(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkEpisodeGallery PRIMARY KEY (id)
);

CREATE TABLE my_Genres
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    genre character varying(32) NOT NULL,
    CONSTRAINT pkGenres PRIMARY KEY (id)
);

-- 20

CREATE TABLE my_GenreGame
(
    gameId int REFERENCES my_Game(id) ON DELETE CASCADE NOT NULL,
    genreId int REFERENCES my_Genres(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkGenreGame PRIMARY KEY (gameId, genreId)
);

CREATE TABLE my_GenreMovie
(
    movieId int REFERENCES my_Movie(id) ON DELETE CASCADE NOT NULL,
    genreId int REFERENCES my_Genres(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkGenreMovie PRIMARY KEY (movieId, genreId)
);

CREATE TABLE my_GenreBook
(
    bookId int REFERENCES my_Book(id) ON DELETE CASCADE NOT NULL,
    genreId int REFERENCES my_Genres(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkGenreBook PRIMARY KEY (bookId, genreId)
);

CREATE TABLE my_GenreSeries
(
    seriesId int REFERENCES my_Series(id) ON DELETE CASCADE NOT NULL,
    genreId int REFERENCES my_Genres(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkGenreSeries PRIMARY KEY (seriesId, genreId)
);

CREATE TABLE my_VideoGame
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    link text NOT NULL,
    gameId int REFERENCES my_Game(id) ON DELETE CASCADE NOT NULL,    
    CONSTRAINT pkVideoGame PRIMARY KEY (id)
);

-- 25

CREATE TABLE my_VideoMovie
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    link text NOT NULL,
    movieId int REFERENCES my_Movie(id) ON DELETE CASCADE NOT NULL,    
    CONSTRAINT pkVideoMovie PRIMARY KEY (id)
);

CREATE TABLE my_VideoBook
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    link text NOT NULL,
    bookId int REFERENCES my_Book(id) ON DELETE CASCADE NOT NULL,    
    CONSTRAINT pkVideoBook PRIMARY KEY (id)
);

CREATE TABLE my_VideoSeries
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    link text NOT NULL,
    seriesId int REFERENCES my_Series(id) ON DELETE CASCADE NOT NULL,    
    CONSTRAINT pkVideoSeries PRIMARY KEY (id)
);

CREATE TABLE my_VideoSeason
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    link text NOT NULL,
    seasonId int REFERENCES my_Season(id) ON DELETE CASCADE NOT NULL,    
    CONSTRAINT pkVideoSeson PRIMARY KEY (id)
);

CREATE TABLE my_VideoEpisode
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    link text NOT NULL,
    episodeId int REFERENCES my_Episode(id) ON DELETE CASCADE NOT NULL,    
    CONSTRAINT pkVideoEpisode PRIMARY KEY (id)
);

-- 30

CREATE TABLE my_Assignment
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    assignment character varying(32) NOT NULL,
    description text,    
    CONSTRAINT pkAssignment PRIMARY KEY (id)
);

CREATE TABLE my_Celebrity
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    name character varying(64) NOT NULL,
    photo bytea,
    birthday date,
    biography text,
    CONSTRAINT pkCelebrity PRIMARY KEY (id)
);

CREATE TABLE my_CelebrityGallery
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    photo bytea NOT NULL,
    celebrityId int REFERENCES my_Celebrity(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkCelebrityGallery PRIMARY KEY (id)
);

CREATE TABLE my_CelebrityAssignmentGame
(
    celebrityId int REFERENCES my_Celebrity(id) ON DELETE CASCADE NOT NULL,
    assignmentId int REFERENCES my_Assignment(id) ON DELETE CASCADE NOT NULL,
    gameId int REFERENCES my_Game(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkCelebrityAssignmentGame PRIMARY KEY (celebrityId, assignmentId, gameId)
);

CREATE TABLE my_CelebrityAssignmentMovie
(
    celebrityId int REFERENCES my_Celebrity(id) ON DELETE CASCADE NOT NULL,
    assignmentId int REFERENCES my_Assignment(id) ON DELETE CASCADE NOT NULL,
    movieId int REFERENCES my_Movie(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkCelebrityAssignmentMovie PRIMARY KEY (celebrityId, assignmentId, movieId)
);

-- 35

CREATE TABLE my_CelebrityAssignmentBook
(
    celebrityId int REFERENCES my_Celebrity(id) ON DELETE CASCADE NOT NULL,
    assignmentId int REFERENCES my_Assignment(id) ON DELETE CASCADE NOT NULL,
    bookId int REFERENCES my_Book(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkCelebrityAssignmentBook PRIMARY KEY (celebrityId, assignmentId, bookId)
);

CREATE TABLE my_CelebrityAssignmentSeries
(
    celebrityId int REFERENCES my_Celebrity(id) ON DELETE CASCADE NOT NULL,
    assignmentId int REFERENCES my_Assignment(id) ON DELETE CASCADE NOT NULL,
    seriesId int REFERENCES my_Series(id) ON DELETE CASCADE NOT NULL,
    CONSTRAINT pkCelebrityAssignmentSeries PRIMARY KEY (celebrityId, assignmentId, seriesId)
);

CREATE TABLE my_User
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    name character varying(64) NOT NULL,
    password character varying(128) NOT NULL,
    email character varying(256) NOT NULL UNIQUE,
    photo bytea,
    birthday date,
    description text,
    creationDate date DEFAULT CURRENT_DATE,
    canEdit boolean DEFAULT false, 
    isSystemAdmin boolean DEFAULT false,
    CONSTRAINT pkUser PRIMARY KEY (id)
);

CREATE TABLE my_GameRating
(
    userId int REFERENCES my_User(id) ON DELETE CASCADE NOT NULL,
    gameId int REFERENCES my_Game(id) ON DELETE CASCADE NOT NULL,
    rate double precision,
    CONSTRAINT pkGameRating PRIMARY KEY (userId, gameId)
);

CREATE TABLE my_MovieRating
(
    userId int REFERENCES my_User(id) ON DELETE CASCADE NOT NULL,
    movieId int REFERENCES my_Movie(id) ON DELETE CASCADE NOT NULL,
    rate double precision,
    CONSTRAINT pkMovieRating PRIMARY KEY (userId, movieId)
);

-- 40

CREATE TABLE my_BookRating
(
    userId int REFERENCES my_User(id) ON DELETE CASCADE NOT NULL,
    bookId int REFERENCES my_Book(id) ON DELETE CASCADE NOT NULL,
    rate double precision,
    CONSTRAINT pkBookRating PRIMARY KEY (userId, bookId)
);

CREATE TABLE my_GameComments
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    userId int REFERENCES my_User(id) ON DELETE CASCADE NOT NULL,
    gameId int REFERENCES my_Game(id) ON DELETE CASCADE NOT NULL,
    comment text,
    responseTo integer REFERENCES my_GameComments(id) ON DELETE CASCADE CHECK (responseTo <> id),
    CONSTRAINT pkGameComments PRIMARY KEY (id)
);

CREATE TABLE my_MovieComments
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    userId int REFERENCES my_User(id) ON DELETE CASCADE NOT NULL,
    movieId int REFERENCES my_Movie(id) ON DELETE CASCADE NOT NULL,
    comment text,
    responseTo integer REFERENCES my_MovieComments(id) ON DELETE CASCADE CHECK (responseTo <> id),
    CONSTRAINT pkMovieComments PRIMARY KEY (id)
);

CREATE TABLE my_BookComments
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    userId int REFERENCES my_User(id) ON DELETE CASCADE NOT NULL,
    bookId int REFERENCES my_Book(id) ON DELETE CASCADE NOT NULL,
    comment text,
    responseTo integer REFERENCES my_BookComments(id) ON DELETE CASCADE CHECK (responseTo <> id),
    CONSTRAINT pkBookComments PRIMARY KEY (id)
);

CREATE TABLE my_SeriesComments
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    userId int REFERENCES my_User(id) ON DELETE CASCADE NOT NULL,
    seriesId int REFERENCES my_Series(id) ON DELETE CASCADE NOT NULL,
    comment text,
    responseTo integer REFERENCES my_SeriesComments(id) ON DELETE CASCADE CHECK (responseTo <> id),
    CONSTRAINT pkSeriesComments PRIMARY KEY (id)
);

-- 45

CREATE TABLE my_EpisodeRating
(
    userId int REFERENCES my_User(id) ON DELETE CASCADE NOT NULL,
    episodeId int REFERENCES my_Episode(id) ON DELETE CASCADE NOT NULL,
    rate double precision,
    CONSTRAINT pkEpisodeRating PRIMARY KEY (userId, episodeId)
);

CREATE TABLE my_EpisodeComments
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ,
    userId int REFERENCES my_User(id) ON DELETE CASCADE NOT NULL,
    episodeId int REFERENCES my_Episode(id) ON DELETE CASCADE NOT NULL,
    comment text,
    responseTo integer REFERENCES my_EpisodeComments(id) ON DELETE CASCADE CHECK (responseTo <> id),
    CONSTRAINT pkEpisodeComments PRIMARY KEY (id)
);

DROP TABLE my_EpisodeComments, my_EpisodeRating, my_SeriesComments, my_BookComments, my_MovieComments, my_GameComments, my_BookRating, my_MovieRating, my_GameRating, my_User, my_CelebrityAssignmentSeries, my_CelebrityAssignmentBook, my_CelebrityAssignmentMovie, my_CelebrityAssignmentGame, my_CelebrityGallery, my_Celebrity, my_Assignment, my_VideoEpisode, my_VideoSeason, my_VideoSeries, my_VideoBook, my_VideoMovie, my_VideoGame, my_GenreSeries, my_GenreBook, my_GenreMovie, my_GenreGame, my_Genres, my_EpisodeGallery, my_Episode, my_SeasonGallery, my_Season, my_SeriesGallery, my_Series, my_Book, my_PublishingCompany, my_MovieGallery, my_Movie, my_Developers, my_GameGallery, my_Game, my_Saga, my_Engine, my_ParentAdvisory, my_Company